#objectives: 
#    1) build pipeline for one as control (Runx1 - MA0002.3)
#    2) up-sclae it for all TFs 

#on the HPC: 
cd /scratch/prj/mmg_holland_sandbox/Yanjing
srun -p cpu --ntasks 1 --nodes 1 --mem=16G --time=04:00:00 --pty /bin/bash -l

#load mamba before data analysis 
mamba activate prj
mamba install -c bioconda bioconductor-jaspar2020 #database is constantly maintained
module load r 
R

#in R: 
setwd("/scratch/prj/mmg_holland_sandbox/Yanjing")

library(Biostrings)
library(JASPAR2020)
library(TFBSTools)
library(tidyr)
library(dplyr)
library(seqLogo)
library(purrr)
library(ggplot2)
library(scales)
library(readxl)
library(GenomicRanges)

fa_path <- "/scratch/prj/mmg_holland_sandbox/_genomes/mouse/GRCm38.p0/rdna/BK000964.3.looped.fasta"

#load modified rDNA sequence 
fa_genome <- readDNAStringSet(fa_path, use.names = TRUE)
fa_seq <- fa_genome[[1]]

#extract Runx1 data from JASPAR2020 database

pfm <- getMatrixByID(JASPAR2020, ID="MA0002.2")
pwm <- toPWM(pfm, type="log2probratio", pseudocounts=0.8,
             bg=c(A=0.25, C=0.25, G=0.25, T=0.25)) #default background settings 

subject <- DNAString(fa_seq)

#distribution of hits 

setwd("/scratch/prj/mmg_holland_sandbox/Yanjing/Runx1/distribution_of_hits")

scores <- seq(50,95, by = 5)

for (s in scores) {
    min_score <- paste0(s, "%")
    siteset <- searchSeq(pwm, subject, seqname="modified_rDNA", min.score=min_score, strand="+")
    siteset_df <- as.data.frame(siteset)
    file_name <- paste0("Runx1_", s, ".csv")
    write.table(siteset_df, file_name, col.names=TRUE) #saving file 
}

##Rplot: plotting hits with different min.score set to determine the knee of the graph

files <- list.files(path = "./", pattern = "\\.csv$", full.names = TRUE)
counts_df <- list.files(path = "./", pattern = "\\.csv$", full.names = TRUE) %>%
  set_names() %>%
  map_df(~ data.frame(row_count = nrow(read.csv(.x))), .id = "file_name")
  
counts_df["min.score"] <- scores
write.table(counts_df, "distribution_of_hits.csv", col.names = TRUE)

p <- ggplot(data = counts_df,aes(min.score, row_count)) + geom_point(aes(colour = "red")) + geom_smooth(method="loess", colour="black", se = FALSE) + labs(x="min.score(%)", y = "Number of hits", title = "Distribution of hits for Runx1") + theme_minimal() + theme(legend.position = "none", axis.text = element_text(size=10), axis.title = element_text(size = 12), title = element_text(size=16))

ggsave("distribution_of_hits.pdf", plot = p, width = 8, height = 6, dpi = 300)

#knee of the plot determined to be at min.score = 75%

##Rplot: violin plot with y = relScore, x = min.score 

violin_table <- map_df(scores, function(s) {
    file_name <- paste0("Runx1_", s, ".csv")
    read.table(file_name, header = TRUE) %>% 
        mutate(min.score = s) %>% #mutate() is column creator and editor
        select(relScore, min.score)
})

head(violin_table)
#       relScore min.score
#1...1 0.6829987        50
#2...2 0.6477694        50
#3...3 0.6661956        50
#4...4 0.5155643        50
#5...5 0.5522765        50
#6...6 0.6002571        50

p_violin <- ggplot(data = violin_table, aes(x = factor(min.score), y = relScore)) +
  geom_violin(
      aes(fill = factor(min.score)),
      scale = "width",
      colour = "darkblue",
      alpha = 0.7
  ) + geom_boxplot(width = 0.1, color = "black", outlier.shape = NA) + 
  labs( x = "min.score(%)", y = "relScore", title = "Distribution of relative scores at different thresholds", fill = "min.score(%)") + theme_minimal()

ggsave("violin_plot.pdf", plot = p_violin, width = 6, height = 4)

#confirmed min.score = 75% is inclusive enough 

setwd("/scratch/prj/mmg_holland_sandbox/Yanjing/Runx1")
siteset <- searchSeq(pwm, subject, seqname="modified_rDNA", min.score="75%", strand="+")
head(siteset)
#An object of class SiteSet with 6 site sequences
#        seqname source feature start end      score strand frame
#1 modified_rDNA   TFBS    TFBS   121 131 -0.5357653      +     .
#2 modified_rDNA   TFBS    TFBS   153 163  5.5944823      +     .
#3 modified_rDNA   TFBS    TFBS   235 245 -0.4157078      +     .
#4 modified_rDNA   TFBS    TFBS   281 291  7.7659549      +     .
#5 modified_rDNA   TFBS    TFBS   291 301  0.9544070      +     .
#6 modified_rDNA   TFBS    TFBS   327 337  2.6416106      +     .
#                                               attributes
#1 TF=RUNX1;class=Runt domain factors;sequence=CGATGAGGGGA
#2 TF=RUNX1;class=Runt domain factors;sequence=TTTTCTGGCCA
#3 TF=RUNX1;class=Runt domain factors;sequence=AGCACTGTTTT
#4 TF=RUNX1;class=Runt domain factors;sequence=GGGTGTGGGTG
#5 TF=RUNX1;class=Runt domain factors;sequence=GAGTGAGGGCG
#6 TF=RUNX1;class=Runt domain factors;sequence=GTGAGTGGCCG

#parameters: 
head(writeGFF3(siteset))
relScore(siteset)
# pvalues(siteset, type="TFMPvalue")
# pvalues(siteset, type="sampling") 

siteset_df <- as.data.frame(siteset)
write.table(siteset_df, "Runx1_75.csv", col.names=TRUE)

##Rplot: ICM for motifs of Runx1 mapped with rDNA at min.score = 75% 
seqs <- siteset_df$siteSeqs 
pfm <- consensusMatrix(DNAStringSet(seqs)) #convert and create a consensus matrix

#consensusMatrix() added empty M & R rows, we remove them: 
pfm <- pfm[c("A", "C", "G", "T"), ]
head(pfm) #data is in counts of occurrences of ACGT 
#convert counts to proportions 
pfm_norm <- prop.table(pfm, margin = 2)
p <- makePWM(pfm_norm)
#save 
pdf("Runx1_75.pdf", width = 7, height = 5)
seqLogo(p)
dev.off() #tells R to stop painting

##Rplot: mapping TFBS to modified rDNA (3.08k at the end is joint to the beginning)
#note: TFBSs are adjusted to modified rDNA positions but the x-axis was shifted by -3.08k to the left, graphs are technically 1k off) 

p_mapping <- ggplot (data = siteset_df, aes(start - 3008)) + geom_histogram(bins = 500) + labs (title = "Runx1 Binding Sites", x = "Position (kb)", y = "No. of Reads") + theme_minimal() + scale_x_continuous(labels = label_number(scale = 1e-3, suffix = "k"), limits = c(-2300,13500)) #data removed outside of [-2.3kb, 13.5kb]

#load supplementary data with SNVs, within [-2293,13357] originally
snv <- read_excel("/scratch/prj/mmg_holland_sandbox/Yanjing/supplementary_data/13059_2022_2617_MOESM2_ESM.xlsx", sheet = 1)

# converting SNV positions to match that of modified rDNA: 

# original code 
# ref_pos <- c(-133, -132. -104) # 2876, 2877 & 2905 
# ref_pos <- ifelse(ref_pos >= 1, ref_pos + 3008, ref_pos + 1 + 3008) 

# modified code 
ref_pos <- snv$SNV
ref_pos <- ifelse(ref_pos >= 1, ref_pos + 3008, ref_pos + 1 + 3008)

snv$ref_pos <- ref_pos
snv <- snv %>% 
    select (SNV,ref_pos, REF, ALT, Haplotype) %>% 
    rename(original = SNV, modified = ref_pos, target_base = REF, alt_base = ALT, haplotype = Haplotype)

write.table(snv, "/scratch/prj/mmg_holland_sandbox/Yanjing/supplementary_data/snv.csv", col.names=TRUE)

p_rug <- p_mapping + 
  geom_rug(data = data.frame(ref_pos), 
           aes(x = ref_pos - 3008), 
           sides = "b", 
           colour = "red", 
           alpha = 0.5) 

ggsave("rug_plot.pdf", plot = p_rug, width = 8, height = 4) 

#mapping hits (TFBS-rDNA) to SNVs: 
snv_range <- GRanges(
    seqnames = "modified_rDNA",
    ranges = IRanges(start=ref_pos, end=ref_pos), #SNV coordinate 
    strand = '+')

hits_range <- makeGRangesFromDataFrame(siteset_df, keep.extra.columns=TRUE)
hits_range$snv_presence <- countOverlaps(hits_range, snv_range) #y is mapped to x and [x,y] 
snv_hits <- hits_range[hits_range$snv_presence > 0]
length(snv_hits) # 29 out of 1885
    #1 means SNV falls within exactly one region (inside specific gene) 
    #2 means SNV falls in area where multiple regions overlap 

#hits not covered by SNVs: 
snv_range$overlap_count <-countOverlaps(snv_range, hits_range)
abs_snv <- snv_range[snv_range$overlap_count == 0] #there is absolutely no coverage on the SNV
length(abs_snv) # 60

snv_range$is_matched <- countOverlaps(snv_range, hits_range) > 0
sum(snv_range$is_matched == TRUE) #28 

snv_range$not_matched <- countOverlaps(snv_range, hits_range) == 0
sum(snv_range$not_matched == TRUE) #60 - this is in respect to SNVs being covered by hits (of TFBS mapped to rDNA) which should add up to the total no. of SNVs (88)

head(snv_range)
#           seqnames    ranges strand | overlap_count is_matched not_matched
#              <Rle> <IRanges>  <Rle> |     <integer>  <logical>   <logical>
#  [1] modified_rDNA       716      + |             0      FALSE        TRUE
#  [2] modified_rDNA       795      + |             1       TRUE       FALSE
#  [3] modified_rDNA      1232      + |             1       TRUE       FALSE
#  [4] modified_rDNA      1596      + |             0      FALSE        TRUE
#  [5] modified_rDNA      1608      + |             0      FALSE        TRUE
#  [6] modified_rDNA      1617      + |             0      FALSE        TRUE

head(hits_range)
#           seqnames    ranges strand |      source     feature  absScore
#              <Rle> <IRanges>  <Rle> | <character> <character> <numeric>
#  [1] modified_rDNA   121-131      + |        TFBS        TFBS -0.535765
#  [2] modified_rDNA   153-163      + |        TFBS        TFBS  5.594482
#  [3] modified_rDNA   235-245      + |        TFBS        TFBS -0.415708
#  [4] modified_rDNA   281-291      + |        TFBS        TFBS  7.765955
#  [5] modified_rDNA   291-301      + |        TFBS        TFBS  0.954407
#  [6] modified_rDNA   327-337      + |        TFBS        TFBS  2.641611
#       relScore          ID          TF               class    siteSeqs
#      <numeric> <character> <character>         <character> <character>
#  [1]  0.771663    MA0002.2       RUNX1 Runt domain factors CGATGAGGGGA
#  [2]  0.857922    MA0002.2       RUNX1 Runt domain factors TTTTCTGGCCA
#  [3]  0.773352    MA0002.2       RUNX1 Runt domain factors AGCACTGTTTT
#  [4]  0.888477    MA0002.2       RUNX1 Runt domain factors GGGTGTGGGTG
#  [5]  0.792631    MA0002.2       RUNX1 Runt domain factors GAGTGAGGGCG
#  [6]  0.816372    MA0002.2       RUNX1 Runt domain factors GTGAGTGGCCG
#      snv_presence
#         <integer>
#  [1]            0
#  [2]            0
#  [3]            0
#  [4]            0
#  [5]            0
#  [6]            0

write.table(snv_range, "hits_mapped_to_snvs.csv")
write.table(hits_range, "snvs_mapped_to_hits.csv")

##Rplot - box plots: 
#1) Rate of hits covered by SNVs/total hits 
rate <- c(nrow(siteset_df),length(snv_hits))
snv_coverage <- c(88,sum(snv_range$is_matched == TRUE),sum(snv_range$not_matched == TRUE)) #note: 88 is the total no. of SNVs which == nrow(snv)

df <- data.frame(category=c("Total hits","Hits containing SNVs"), count=rate)
p <- ggplot(df,aes(x=factor(category,levels=category),y=count, fill = category)) + 
    geom_bar(stat="identity", colour ="darkgrey") + 
    scale_fill_manual(values = c("skyblue", "salmon")) +
    labs(title = "Runx1 binding sites in rDNA", x = "", y = "Number of hits") +
    theme_minimal() + theme(legend.title = element_blank())

ggsave("bar_plot_hits.pdf", plot = p, width = 8, height = 8)

#2) SNVs affecting TFBS (88 SNVs) 
df <- data.frame(category=c("Total","Covered by hits","Uncovered by hits"), count=snv_coverage)
a <- ggplot(df,aes(x=factor(category,levels=category),y=count, fill = category)) + 
    geom_bar(stat="identity", colour ="darkgrey") + 
    scale_fill_manual(values = c("pink", "salmon", "skyblue")) +
    labs(title = "Mouse SNVs compared to Runx1 binding sites in rDNA", x = "", y = "Number of SNVs") +
    theme_minimal() + theme(legend.title = element_blank())
    
ggsave("bar_plot_snv.pdf", plot = a, width = 8, height = 8)

#creating results table
#get covered snv positions 
snv_covered <- as.data.frame(snv_range) %>% 
  filter(is_matched == TRUE) %>%
  pull(start,overlap_count)

snv_df <- as.data.frame(snv)
hits_df <- as.data.frame(hits_range)

# expand each TFBS across its 11 positions, filter to SNV positions, add base
results <- siteset_df %>%
  mutate(
    base = strsplit(as.character(siteSeqs), ""),
    pos  = mapply(seq, start, end, SIMPLIFY = FALSE) #pos=of the affected base on TFBS
  ) %>%
  unnest(c(base, pos)) %>% #base affected calculated 
  filter(pos %in% snv_covered) %>%
  left_join(hits_df %>% select(start, snv_presence), by = c("start"="start")) %>%
  left_join(snv_df, by = c("pos" = "modified")) %>% 
  rename(snv_modified = pos, snv_original = original) %>%
  select(seqnames, start, end, absScore, relScore, ID, TF, siteSeqs, base, snv_presence, snv_modified, snv_original, target_base, alt_base, haplotype)

#checking that it is correct: all base == target_base 
all(results$base == results$target_base) #TRUE thus remove base
results$base <- NULL

nrow(results) #35
head(results)
#   seqnames start   end absScore relScore ID    TF    siteSeqs base  snv_presence
#  <chr>    <int> <int>    <dbl>    <dbl> <chr> <chr> <chr>    <chr>        <int>
#1 modifie…   788   798    3.55     0.829 MA00… RUNX1 TGTATTG… G                1
#2 modifie…  1232  1242    0.361    0.784 MA00… RUNX1 CGCTTCG… C                1
#3 modifie…  2825  2835    4.47     0.842 MA00… RUNX1 TTCTCCG… G                1
#4 modifie…  3173  3183    1.89     0.806 MA00… RUNX1 GCTTGCG… T                1
#5 modifie…  3177  3187    4.78     0.846 MA00… RUNX1 GCGTGTG… T                1
#6 modifie…  3366  3376   -1.69     0.755 MA00… RUNX1 ACCTCCG… A                1
# ℹ 5 more variables: snv_modified <dbl>, snv_original <dbl>,
#   target_base <chr>, alt_base <chr>, haplotype <chr>

#compare to Runx1 data on JASPAR2020 which is based off of WGS
pfm <- getMatrixByID(JASPAR2020, ID="MA0002.2") #repeat bcos currently pfm is for TF-rDNA 
pwm <- toPWM(pfm, type="log2probratio", pseudocounts=0.8,
             bg=c(A=0.25, C=0.25, G=0.25, T=0.25))
             
print(pfm) #for counts 
#  [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11]
#A  287  234  123   57    0   87    0   17   10   131   500
#C  496  485 1072    0   75  127    0   42  400   463   158
#G  696  467  149    7 1872   70 1987 1848  251    81   289
#T  521  814  656 1936   53 1716   13   93 1339  1325  1053

pfm_mat <- Matrix(pfm)
colnames(pfm_mat) <- paste0("Pos", 1:ncol(pfm_mat))

#calculate total 
pfm_df <- as.data.frame(pfm_mat)
pfm_table <- rbind(pfm_df, Total = colSums(pfm_df))
print(pfm_table)

#      Pos1 Pos2 Pos3 Pos4 Pos5 Pos6 Pos7 Pos8 Pos9 Pos10 Pos11
#A      287  234  123   57    0   87    0   17   10   131   500
#C      496  485 1072    0   75  127    0   42  400   463   158
#G      696  467  149    7 1872   70 1987 1848  251    81   289
#T      521  814  656 1936   53 1716   13   93 1339  1325  1053
#Total 2000 2000 2000 2000 2000 2000 2000 2000 2000  2000  2000

write.table(pfm_table, "pfm_counts.csv", col.names = TRUE)

#x = start of the BS which starts at 1 
#y = position of the SNV 

x <- results$start
y <- results$snv_modified

#position z: the base being affected by the SNV on the TFBS sequence i.e. out of 11 for Runx1 
z = y - x + 1
head(z) #double checked, length = 35

o <- results$snv_original

df <- data.frame(snv_original = o, snv_modified = y, position_z = z)
df$target_base <- c(results$target_base)
df$alt_base <- c(results$alt_base)

print(df)

write.table(df, "position_z.csv")

#for both ref/target base and alt base calculate the rate: G over total 

totals <- as.numeric(pfm_table["Total", ])
names(totals) <- 1:ncol(pfm_mat)

df$target_rate <- mapply(function(pos, base) {
  val <- pfm_mat[base, pos] / totals[pos]
  if (val == 0) "error" else val
}, df$position_z, df$target_base)

df$alt_rate <- mapply(function(pos, base) {
  val <- pfm_mat[base, pos] / totals[pos]
  if (val == 0) "intolerable" else val
}, df$position_z, df$alt_base)

t <- as.numeric(ifelse(df$target_rate == "intolerable", NA, df$target_rate))
a <- as.numeric(ifelse(df$alt_rate == "intolerable", NA, df$alt_rate))

df$diff <- a - t 

write.table(df, "results_TFBSrate.csv")
